### ISSUE TITLE
Minimal reproducer of Kotlin, Hibernate and GraalVM native executable fails at SessionFactoryPerDataSourceFactory.buildHibernateSessionFactoryBuilder

### ISSUE THREAD

**Issue by ArnauAregall** [micronaut-projects/micronaut-sql#1203]
### Expected Behavior

A minimal Micronaut Kotlin Hibernate application created from `mn` CLI should run without errors when executed from it's native executable generated with GraalVM.

### Actual Behaviour

When running a GraalVM native executable from minimal Micronaut Hibernate application created from `mn` CLI, the context fails to start because `SessionFactoryPerDataSourceFactory#buildHibernateSessionFactoryBuilder` cannot create a `org.hibernate.SessionFactory` bean (see full stacktrace below).

I have confirmed JDBC can acquire the DataSource connection via Flyway and migrations are applied.

```text
07:22:32.826 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [org.hibernate.SessionFactory] could not be loaded: Error instantiating bean of type  [org.hibernate.SessionFactory]

Message: No classes have been predefined during the image build to load from bytecodes at runtime.
Path Taken: SessionFactoryPerDataSourceFactory.buildHibernateSessionFactoryBuilder(SessionFactoryBuilder sessionFactoryBuilder) --> SessionFactoryPerDataSourceFactory.buildHibernateSessionFactoryBuilder([SessionFactoryBuilder sessionFactoryBuilder])
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [org.hibernate.SessionFactory] could not be loaded: Error instantiating bean of type  [org.hibernate.SessionFactory]

Message: No classes have been predefined during the image build to load from bytecodes at runtime.
Path Taken: SessionFactoryPerDataSourceFactory.buildHibernateSessionFactoryBuilder(SessionFactoryBuilder sessionFactoryBuilder) --> SessionFactoryPerDataSourceFactory.buildHibernateSessionFactoryBuilder([SessionFactoryBuilder sessionFactoryBuilder])
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1980)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:291)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3322)
	at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3677)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:361)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:199)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:73)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:322)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:297)
	at com.example.AppKt.main(App.kt:17)
	at java.base@21.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [org.hibernate.SessionFactory]

Message: No classes have been predefined during the image build to load from bytecodes at runtime.
Path Taken: SessionFactoryPerDataSourceFactory.buildHibernateSessionFactoryBuilder(SessionFactoryBuilder sessionFactoryBuilder) --> SessionFactoryPerDataSourceFactory.buildHibernateSessionFactoryBuilder([SessionFactoryBuilder sessionFactoryBuilder])
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2324)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2279)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2291)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3054)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2956)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2917)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2730)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1729)
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2165)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1328)
	at io.micronaut.configuration.hibernate.jpa.conf.$SessionFactoryPerDataSourceFactory$BuildHibernateSessionFactoryBuilder4$Definition.instantiate(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.instantiate(BeanDefinitionDelegate.java:159)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2309)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2279)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2291)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3054)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2956)
	at io.micronaut.context.DefaultBeanContext.initializeEagerBean(DefaultBeanContext.java:2667)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1974)
	... 10 common frames omitted
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: No classes have been predefined during the image build to load from bytecodes at runtime.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:121)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.PredefinedClassesSupport.throwNoBytecodeClasses(PredefinedClassesSupport.java:76)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.PredefinedClassesSupport.loadClass(PredefinedClassesSupport.java:130)
	at java.base@21.0.1/java.lang.ClassLoader.defineClass(ClassLoader.java:280)
	at net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader.invoker(JavaDispatcher.java:1383)
	at net.bytebuddy.utility.dispatcher.JavaDispatcher$InvokerCreationAction.run(JavaDispatcher.java:459)
	at net.bytebuddy.utility.dispatcher.JavaDispatcher$InvokerCreationAction.run(JavaDispatcher.java:452)
	at java.base@21.0.1/java.security.AccessController.executePrivileged(AccessController.java:129)
	at java.base@21.0.1/java.security.AccessController.doPrivileged(AccessController.java:319)
	at net.bytebuddy.utility.dispatcher.JavaDispatcher.doPrivileged(JavaDispatcher.java)
	at net.bytebuddy.utility.dispatcher.JavaDispatcher.<clinit>(JavaDispatcher.java:87)
	at net.bytebuddy.description.type.TypeDescription$ForLoadedType.<clinit>(TypeDescription.java:8659)
	at net.bytebuddy.matcher.ElementMatchers.isFinalizer(ElementMatchers.java:1624)
	at org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState$ProxyDefinitionHelpers.<init>(ByteBuddyState.java:296)
	at org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState.<clinit>(ByteBuddyState.java:71)
	at org.hibernate.bytecode.internal.bytebuddy.BytecodeProviderImpl.<init>(BytecodeProviderImpl.java:124)
	at org.hibernate.bytecode.internal.bytebuddy.BytecodeProviderImpl.<init>(BytecodeProviderImpl.java:116)
	at org.hibernate.bytecode.internal.BytecodeProviderInitiator.buildBytecodeProvider(BytecodeProviderInitiator.java:59)
	at org.hibernate.bytecode.internal.BytecodeProviderInitiator.initiateService(BytecodeProviderInitiator.java:36)
	at org.hibernate.bytecode.internal.BytecodeProviderInitiator.initiateService(BytecodeProviderInitiator.java:22)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:119)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:264)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:239)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:216)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.<init>(SessionFactoryBuilderImpl.java:69)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.<init>(SessionFactoryBuilderImpl.java:46)
	at org.hibernate.boot.internal.DefaultSessionFactoryBuilderService.createSessionFactoryBuilder(DefaultSessionFactoryBuilderService.java:26)
	at org.hibernate.boot.internal.MetadataImpl.getSessionFactoryBuilder(MetadataImpl.java:170)
	at io.micronaut.configuration.hibernate.jpa.conf.AbstractHibernateFactory.buildHibernateSessionFactoryBuilder(AbstractHibernateFactory.java:96)
	at io.micronaut.configuration.hibernate.jpa.conf.SessionFactoryPerDataSourceFactory.buildHibernateSessionFactoryBuilder(SessionFactoryPerDataSourceFactory.java:100)
	at io.micronaut.configuration.hibernate.jpa.conf.$SessionFactoryPerDataSourceFactory$BuildHibernateSessionFactoryBuilder3$Definition.doInstantiate(Unknown Source)
	at io.micronaut.context.AbstractInitializableBeanDefinition.instantiate(AbstractInitializableBeanDefinition.java:774)
	at io.micronaut.context.BeanDefinitionDelegate.instantiate(BeanDefinitionDelegate.java:156)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2309)
	... 31 common frames omitted
```

Additionally I have tried disabling Hibernate bytecode optimizations (`-Dhibernate.bytecode.use_reflection_optimizer=false`) without success.

### Steps To Reproduce

I have created the following repository with a minimal reproducer ready to clone and check: [ArnauAregall/micronaut-hibernate-native-reproducer](https://github.com/ArnauAregall/micronaut-hibernate-native-reproducer
)

Anyhow this is how to build a minimal reproducer:

**Run the `mn create-app`**:

```shell
$ sdk install micronaut 4.2.2

$ mn create-app --build=gradle_kotlin --jdk=21 --lang=kotlin --test=junit --features=data-jpa,hibernate-jpa,flyway,postgres com.example.demo
```

**application.yml**:

```yml
micronaut:
  application:
    name: micronaut-hibernate-native-reproducer

datasources:
  default:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=demo
    username: postgres
    password: postgres

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none

flyway:
  datasources:
    default:
      enabled: true
      default-schema: demo
      locations:
        - db/migrations
```

**Flyway migration file under `src/kotlin/resources/db/migration`**:

```sql
CREATE TABLE person  (
    id BIGSERIAL UNIQUE NOT NULL,
    name VARCHAR NOT NULL,
    PRIMARY KEY (id)
);
```

**Minimal Kotlin Hibernate application**:

```kotlin
package com.example

import io.micronaut.context.event.ApplicationEventListener
import io.micronaut.context.event.StartupEvent
import io.micronaut.data.annotation.Repository
import io.micronaut.data.jpa.repository.JpaRepository
import io.micronaut.runtime.Micronaut.run
import jakarta.inject.Singleton
import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.Table

fun main(args: Array<String>) {
	run(*args)
}

@Entity
@Table(name = "person")
class Person (@Column(name = "name") val name: String) {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	val id: Long? = null

	override fun toString(): String = "Person(name='$name', id=$id)"
}

@Repository
interface PersonRepository: JpaRepository<Person, Long>

@Singleton
class StartupListener(private val personRepository: PersonRepository): ApplicationEventListener<StartupEvent> {

	override fun onApplicationEvent(event: StartupEvent?) {
		personRepository.saveAll(
			listOf(Person("Foo"), Person("Bar"), Person("Baz"))
		)

		personRepository.findAll()
			.forEach { println(it) }
	}
}
```

Finally, run `./gradlew nativeComplie` and execute the native binary (requires Postgres to be running at 5432).

### Environment Information

- Operating System: macOS 14.1
- JDK Version: 21.0.1-graalce
- Gradle wrapper: 8.4
- Kotlin version: 1.9.21
- Micronaut Version: 4.2.2 (Hibernate 6.2.13.Final).

### Example Application

https://github.com/ArnauAregall/micronaut-hibernate-native-reproducer

### Version

4.2.1

**Comment by graemerocher** [comment]
you probably need to use compile time proxies, see https://micronaut-projects.github.io/micronaut-sql/latest/guide/index.html#hibernate-proxies

**Comment by ArnauAregall** [comment]
Hello @graemerocher, thanks a lot for your answer, in my case enabling `compile-time-hibernate-proxies` solved the issue on the reproducer sample and my original project.

```yaml
jpa:
  default:
    compile-time-hibernate-proxies: true
    properties:
      hibernate:
        hbm2ddl:
          auto: none
```
