### ISSUE TITLE
Connection pool exausted using micronaut transaction.

### ISSUE THREAD

**Issue by andcuevas** [micronaut-projects/micronaut-sql#262]
I created an example application to reproduce the problem [here](https://github.com/andcuevas/micronaut-tx-connection-leak).

In order to run this example you need a PostgreSQL database.

Edit the application.yml file and change:
```
datasources:
  default:
    url: jdbc:postgresql://10.211.55.10:5432/prueba
    username: postgres
    password: postgres
```

With your values.

Edit pom.xml and change:
```
<database-url>jdbc:postgresql://10.211.55.10:5432/prueba</database-url>
<database-user>postgres</database-user>
<database-password>postgres</database-password>
```

With your values.

Run the Application class.

If you see in the log that the application is inserting values, like this:
```
13:38:05.001 [pool-2-thread-3] DEBUG i.m.context.DefaultBeanContext - Resolved existing bean [prueba.jdbc.TestScheduler@df35147] for type [class prueba.jdbc.TestScheduler] and qualifier [null]
13:38:05.002 [pool-2-thread-3] DEBUG i.m.t.j.DataSourceTransactionManager - Creating new transaction with name [Dao.insert]: 0,-1
13:38:05.002 [pool-2-thread-3] DEBUG i.m.t.j.DataSourceTransactionManager - Acquired Connection [ProxyConnection[PooledConnection[org.postgresql.jdbc.PgConnection@7f64f3dc]]] for JDBC transaction
13:38:05.003 [pool-2-thread-3] DEBUG org.jooq.tools.LoggerListener - Executing query          : insert into "public"."test_table" ("key", "some_text") values (?, ?)
13:38:05.003 [pool-2-thread-3] DEBUG org.jooq.tools.LoggerListener - -> with bind values      : insert into "public"."test_table" ("key", "some_text") values ('7396b88c-6438-4e9a-bb45-ebdc88f6dce7', 'text.')
13:38:05.004 [pool-2-thread-3] DEBUG org.jooq.tools.LoggerListener - Affected row(s)          : 1
13:38:05.005 [pool-2-thread-3] DEBUG i.m.t.j.DataSourceTransactionManager - Initiating transaction commit
13:38:05.005 [pool-2-thread-3] DEBUG i.m.t.j.DataSourceTransactionManager - Committing JDBC transaction on Connection [ProxyConnection[PooledConnection[org.postgresql.jdbc.PgConnection@7f64f3dc]]]
13:38:05.006 [pool-2-thread-3] DEBUG i.m.t.j.DataSourceTransactionManager - Releasing JDBC Connection [ProxyConnection[PooledConnection[org.postgresql.jdbc.PgConnection@7f64f3dc]]] after transaction
13:38:07.006 [pool-2-thread-2] DEBUG i.m.context.DefaultBeanContext - Resolved existing bean [prueba.jdbc.TestScheduler@df35147] for type [class prueba.jdbc.TestScheduler] and qualifier [null]
13:38:07.006 [pool-2-thread-2] DEBUG i.m.t.j.DataSourceTransactionManager - Creating new transaction with name [Dao.insert]: 0,-1
13:38:07.006 [pool-2-thread-2] DEBUG i.m.t.j.DataSourceTransactionManager - Acquired Connection [ProxyConnection[PooledConnection[org.postgresql.jdbc.PgConnection@7f64f3dc]]] for JDBC transaction
13:38:07.007 [pool-2-thread-2] DEBUG org.jooq.tools.LoggerListener - Executing query          : insert into "public"."test_table" ("key", "some_text") values (?, ?)
13:38:07.007 [pool-2-thread-2] DEBUG org.jooq.tools.LoggerListener - -> with bind values      : insert into "public"."test_table" ("key", "some_text") values ('c772cd4d-3383-44a2-8bfb-e8e3ceff700e', 'text.')
13:38:07.009 [pool-2-thread-2] DEBUG org.jooq.tools.LoggerListener - Affected row(s)          : 1
```

Restart the application, for some reason the problem doesn't happen all the time.

When the problem happens, you will see this in the log at the first insert attempt:
```
13:36:38.723 [pool-2-thread-2] DEBUG org.jooq.tools.LoggerListener - Executing query          : insert into "public"."test_table" ("key", "some_text") values (?, ?)
13:36:38.724 [pool-2-thread-2] DEBUG org.jooq.tools.LoggerListener - -> with bind values      : insert into "public"."test_table" ("key", "some_text") values ('be6d5215-42f9-4b9e-96b3-e1045b8c7eaf', 'text.')
13:37:08.731 [pool-2-thread-2] DEBUG io.micronaut.core.reflect.ClassUtils - Attempting to dynamically load class org.postgresql.Driver
13:37:08.731 [pool-2-thread-2] DEBUG io.micronaut.core.reflect.ClassUtils - Successfully loaded class org.postgresql.Driver
13:37:08.732 [pool-2-thread-2] DEBUG org.jooq.tools.LoggerListener - Exception                
org.jooq.exception.DataAccessException: Error getting connection from data source org.apache.tomcat.jdbc.pool.DataSource@7ff2b8d2{ConnectionPool[defaultAutoCommit=false; defaultReadOnly=null; defaultTransactionIsolation=-1; defaultCatalog=null; driverClassName=org.postgresql.Driver; maxActive=1; maxIdle=1; minIdle=1; initialSize=1; maxWait=30000; testOnBorrow=false; testOnReturn=false; timeBetweenEvictionRunsMillis=5000; numTestsPerEvictionRun=0; minEvictableIdleTimeMillis=60000; testWhileIdle=false; testOnConnect=false; password=********; url=jdbc:postgresql://10.211.55.10:5432/prueba; username=postgres; validationQuery=SELECT 1; validationQueryTimeout=-1; validatorClassName=null; validationInterval=3000; accessToUnderlyingConnectionAllowed=true; removeAbandoned=false; removeAbandonedTimeout=60; logAbandoned=false; connectionProperties=null; initSQL=null; jdbcInterceptors=null; jmxEnabled=true; fairQueue=true; useEquals=true; abandonWhenPercentageFull=0; maxAge=0; useLock=false; dataSource=null; dataSourceJNDI=null; suspectTimeout=0; alternateUsernameAllowed=false; commitOnReturn=false; rollbackOnReturn=false; useDisposableConnectionFacade=true; logValidationErrors=false; propagateInterruptState=false; ignoreExceptionOnPreLoad=false; useStatementFacade=true; }
	at org.jooq_3.13.2.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:86)
	at org.jooq.impl.DefaultExecuteContext.connection(DefaultExecuteContext.java:647)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:334)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:119)
	at prueba.jdbc.Dao.insert(Dao.java:29)
	at prueba.jdbc.$DaoDefinition$Intercepted.$$access0(Unknown Source)
	at prueba.jdbc.$DaoDefinition$Intercepted$$proxy0.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:60)
	at io.micronaut.transaction.interceptor.TransactionalInterceptor.intercept(TransactionalInterceptor.java:108)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at prueba.jdbc.$DaoDefinition$Intercepted.insert(Unknown Source)
	at prueba.jdbc.TestScheduler.handle(TestScheduler.java:22)
	at prueba.jdbc.TestScheduler.run(TestScheduler.java:18)
	at prueba.jdbc.$TestSchedulerDefinition$$exec1.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
	at io.micronaut.inject.DelegatingExecutableMethod.invoke(DelegatingExecutableMethod.java:76)
	at io.micronaut.scheduling.processor.ScheduledMethodProcessor.lambda$process$5(ScheduledMethodProcessor.java:125)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: org.apache.tomcat.jdbc.pool.PoolExhaustedException: [pool-2-thread-2] Timeout: Pool empty. Unable to fetch a connection in 30 seconds, none available[size:1; busy:1; idle:0; lastwait:30000].
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:717)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:198)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:132)
	at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:83)
	... 23 common frames omitted
```

### Environment Information

- **Operating System**: MacOS 10.15.5
- **Micronaut Version:** 2.0.0
- **JDK Version:** 14.0.1
- PostgreSql Version: 11

**Comment by andcuevas** [comment]
I made a debug of the example application I created for this issue. I found a difference when it works without problems and when it fails.

When works without problems:

The class io.micronaut.configuration.jooq.JooqConfigurationFactory receives a datasource of type io.micronaut.transaction.jdbc.TransactionAwareDataSource.DataSourceProxy

When fails:

The class io.micronaut.configuration.jooq.JooqConfigurationFactory receives a datasource of type org.apache.tomcat.jdbc.pool.DataSource

**Comment by andcuevas** [comment]
Debugging the class io.micronaut.context.DefaultBeanContext, the method doCreateBean.
In the code:

```
for (BeanCreatedEventListener listener : entry.getValue()) {
    bean = (T) listener.onCreated(new BeanCreatedEvent(this, beanDefinition, beanKey, bean));
    if (bean == null) {
        throw new BeanInstantiationException(resolutionContext, "Listener [" + listener + "] returned null from onCreated event");
    }
}
```

```entry``` has two values:

1. io.micronaut.transaction.jdbc.TransactionAwareDataSource
2. io.micronaut.flyway.DataSourceMigrationRunnerDefinition

The order of the list determines whether the application works or not.

If I remove micronaut-flyway, the list only has TransactionAwareDataSource and the application works all the time.

**Comment by alvarosanchez** [comment]
I think this is caused by https://github.com/micronaut-projects/micronaut-flyway/blob/master/flyway/src/main/java/io/micronaut/flyway/DataSourceMigrationRunner.java#L56

@ilopmar @graemerocher is there a way around this? Maybe `JooqConfigurationFactory` could check whether the `DataSource` has been resolved already? Or do it in the `DataSourceResolver` implementation?

**Comment by graemerocher** [comment]
@ilopmar probably best placed to answer, not sure what Flyway is doing to cause this

**Comment by alvarosanchez** [comment]
@graemerocher I mentioned you because you changed it in this commit: https://github.com/micronaut-projects/micronaut-flyway/commit/35467e945a59b8babee35e83ee5bb00e35323065#diff-b5158eb97449b43606aafc851eddc31cR57

**Comment by graemerocher** [comment]
Right. If I recall it was because Flyway needed the non-transactional datasource to work correctly

**Comment by alvarosanchez** [comment]
Then maybe https://github.com/micronaut-projects/micronaut-flyway/blob/master/flyway/src/main/java/io/micronaut/flyway/DataSourceMigrationRunner.java#L68 can be changed to return `event.getBean()`?

**Comment by graemerocher** [comment]
it should in fact be `event.getBean()` and this is indeed a major bug in the flyway integration as it is essentially deactivating transaction support when it is present
