### ISSUE TITLE
com.mysql.jdbc.Driver is deprecated

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-sql#364]
Autodetection of the database driver is defaulting to the deprecated version of the MySQL driver:

https://github.com/micronaut-projects/micronaut-sql/blob/master/jdbc/src/main/java/io/micronaut/jdbc/JdbcDatabaseManager.java#L42

This should be replaced with `com.mysql.cj.jdbc.Driver`

**Comment by graemerocher** [comment]
This also means by default things are broken in GraalVM because the feature is looking for the new driver:

https://github.com/micronaut-projects/micronaut-sql/blob/master/jdbc/src/main/java/io/micronaut/jdbc/nativeimage/JdbcFeature.java#L55

So GraalVM fails with:

```
Caused by: java.lang.RuntimeException: Failed to load driver class com.mysql.jdbc.Driver in either of HikariConfig class loader or Thread context classloader
        at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:486)
        at io.micronaut.configuration.jdbc.hikari.DatasourceConfiguration.postConstruct(DatasourceConfiguration.java:70)
        at io.micronaut.configuration.jdbc.hikari.$DatasourceConfigurationDefinition.initialize(Unknown Source)
```

**Comment by graemerocher** [comment]
And actually the new driver is not working on GraalVM:

```
Caused by: java.lang.ClassCastException: com.mysql.cj.exceptions.CJException cannot be cast to com.mysql.cj.exceptions.UnableToConnectException
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833)
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
        ... 26 more
```
