### ISSUE TITLE
Fail to create native images with Micronaut SQL 3.3.0 and Micronaut 2.2.0 snapshot

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-sql#372]
After the release of Microaut SQL 3.3.0 the Micronaut Data JPA test applications fail. This happens for the four test apps: H2, MariaDB, Postgres and MySQL.

See https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/pipelines/216801089

### Steps to Reproduce

- `git clone https://github.com/micronaut-graal-tests/micronaut-data-jpa-graal`
- `cd micronaut-data-jpa-graal`
- `git checkout 2.2.x_h2`
- `sdk use java 20.2.0.r8-grl`
- `./build-native-image.sh`
- `./data-jpa-h2`

### Expected Behaviour

The app should start properly

### Actual Behaviour

It fails with:

```
18:33:50.532 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
18:33:50.536 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
18:33:50.536 [main] INFO  org.hibernate.Version - HHH000412: Hibernate ORM core version [WORKING]
18:33:50.538 [main] INFO  o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
18:33:50.540 [main] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
18:33:50.546 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [org.hibernate.SessionFactory] could not be loaded: Error instantiating bean of type [org.hibernate.SessionFactory]: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [org.hibernate.SessionFactory] could not be loaded: Error instantiating bean of type [org.hibernate.SessionFactory]: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1549)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:220)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2780)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:233)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:166)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:64)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:299)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:285)
	at example.Application.main(Application.java:30)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [org.hibernate.SessionFactory]: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1927)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2647)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2633)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2172)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1543)
	... 8 common frames omitted
Caused by: org.hibernate.MappingException: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
	at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:123)
	at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:77)
	at org.hibernate.metamodel.internal.MetamodelImpl.initialize(MetamodelImpl.java:181)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:301)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:469)
	at io.micronaut.configuration.hibernate.jpa.EntityManagerFactoryBean.hibernateSessionFactory(EntityManagerFactoryBean.java:222)
	at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$HibernateSessionFactory3Definition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:143)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1898)
	... 12 common frames omitted
Caused by: org.hibernate.HibernateException: Unable to instantiate default tuplizer [org.hibernate.tuple.entity.PojoEntityTuplizer]
	at org.hibernate.tuple.entity.EntityTuplizerFactory.constructTuplizer(EntityTuplizerFactory.java:91)
	at org.hibernate.tuple.entity.EntityTuplizerFactory.constructDefaultTuplizer(EntityTuplizerFactory.java:116)
	at org.hibernate.tuple.entity.EntityMetamodel.<init>(EntityMetamodel.java:423)
	at org.hibernate.persister.entity.AbstractEntityPersister.<init>(AbstractEntityPersister.java:608)
	at org.hibernate.persister.entity.SingleTableEntityPersister.<init>(SingleTableEntityPersister.java:128)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:96)
	... 20 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.hibernate.tuple.entity.EntityTuplizerFactory.constructTuplizer(EntityTuplizerFactory.java:88)
	... 26 common frames omitted
Caused by: org.hibernate.InstantiationException: Could not instantiate managed bean directly : io.micronaut.context.BeanContext
	at org.hibernate.resource.beans.internal.FallbackBeanInstanceProducer.produceBeanInstance(FallbackBeanInstanceProducer.java:45)
	at org.hibernate.resource.beans.container.spi.FallbackContainedBean.<init>(FallbackContainedBean.java:23)
	at org.hibernate.resource.beans.internal.ManagedBeanRegistryImpl.getBean(ManagedBeanRegistryImpl.java:58)
	at io.micronaut.configuration.hibernate.jpa.proxy.IntroducedHibernateProxyFactoryFactory.buildProxyFactory(IntroducedHibernateProxyFactoryFactory.java:42)
	at org.hibernate.tuple.entity.PojoEntityTuplizer.buildProxyFactoryInternal(PojoEntityTuplizer.java:125)
	at org.hibernate.tuple.entity.PojoEntityTuplizer.buildProxyFactory(PojoEntityTuplizer.java:94)
	at org.hibernate.tuple.entity.AbstractEntityTuplizer.<init>(AbstractEntityTuplizer.java:160)
	at org.hibernate.tuple.entity.PojoEntityTuplizer.<init>(PojoEntityTuplizer.java:53)
	... 28 common frames omitted
Caused by: java.lang.NoSuchMethodException: io.micronaut.context.BeanContext.<init>()
	at java.lang.Class.getConstructor0(DynamicHub.java:3082)
	at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2178)
	at org.hibernate.resource.beans.internal.FallbackBeanInstanceProducer.produceBeanInstance(FallbackBeanInstanceProducer.java:40)
	... 35 common frames omitted
```

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 2.2.0 snapshot
- **JDK Version:** 1.8

**Comment by graemerocher** [comment]
@dstepanov do you know what this could be? Seems we need a test case for graal when hibernate proxy generation is not enabled

**Comment by graemerocher** [comment]
@ilopmar can you review the PR and test that it works then we will need to release another version

I have tested it myself with your sample app but just want to be double sure

**Comment by ilopmar** [comment]
Done! Works for me :-)

**Comment by dstepanov** [comment]
Strange, the only difference is this:
```java
        if (compileTimeHibernateProxies) {
            // It would be enough to add `ProxyFactoryFactory` by providing `BytecodeProvider` we eliminate bytecode Enhancer
            standardServiceRegistryBuilder.addInitiator(new StandardServiceInitiator<BytecodeProvider>() {
                @Override
                public BytecodeProvider initiateService(Map configurationValues, ServiceRegistryImplementor registry) {
                    return applicationContext.getBean(BytecodeProvider.class);
                }

                @Override
                public Class<BytecodeProvider> getServiceInitiated() {
                    return BytecodeProvider.class;
                }
            });
        }
```

**Comment by graemerocher** [comment]
@dstepanov that is not the case. Since the substitution that was put in place modifies the application https://github.com/micronaut-projects/micronaut-sql/blob/master/hibernate-jpa/src/main/java/io/micronaut/configuration/hibernate/jpa/graal/HibernateSubstitutions.java#L230

**Comment by dstepanov** [comment]
Yes, but that just replaces the need for it. I have tried to run the test without the property and it works 🤔

**Comment by dstepanov** [comment]
@ilopmar Is there a way to reproduce it locally?

**Comment by ilopmar** [comment]
@dstepanov I explained how to test everything locally in this issue. Please note that it happens with the current GraalVM version 20.2.0 so you don't need to compile GraalVM from master branch.

The only thing you may need is the following in the application `build.gradle` to force the snapshot version:

```groovy
repositories {
    mavenLocal() // <---- Add your maven local
   ...
}

configurations {
    // for dependencies that are needed for development only
    developmentOnly

    all {
        resolutionStrategy {
            eachDependency { DependencyResolveDetails details ->
                // specifying a fixed version for all libraries with 'io.micronaut.data' group
                if (details.requested.group == 'io.micronaut.data') {
                    details.useVersion micronautDataVersion
                }
///////////// ADD THIS //////////////////
                if (details.requested.group == 'io.micronaut.sql') {
                    details.useVersion '3.3.1.BUILD-SNAPSHOT'
                }
///////////// ADD THIS //////////////////
            }
        }
    }
}
```

**Comment by dstepanov** [comment]
Looks like `DataEntityManagerFactoryBean` is replacing `StandardServiceRegistry` and it doesn't includes `AvailableSettings.BEAN_CONTAINER`. 

The only difference is:
```java
    Class<?> sessionContextClass = ClassUtils.forName("org.springframework.orm.hibernate5"
                                                        + ".SpringSessionContext", EntityManagerFactoryBean.class.getClassLoader())
                .orElse(MicronautSessionContext.class);
        additionalSettings.put(
                AvailableSettings.CURRENT_SESSION_CONTEXT_CLASS, sessionContextClass.getName());
```
@graemerocher Is it still needed to be replaced? Maybe it can be refactored to use some kind of `CurrentSessionContextProvider`

**Comment by graemerocher** [comment]
yeah it would be nice to get rid of DataEntityManagerFactoryBean
