### ISSUE TITLE
Schema not created in native image 

### ISSUE THREAD

**Issue by pgressa** [micronaut-projects/micronaut-sql#460]
When using native image version of orders app https://github.com/pgressa/oraclecloud-cloudnative/tree/master/src/orders the schema was not created what ended up in stacktrace of:
```
09:47:16.788 [RxCachedThreadScheduler-1] INFO  m.o.s.$OrdersServiceDefinition$Intercepted - Creating order: CustomerOrder [id=null, customer=Customer{customerId=null, id='492a5160-0096-4afa-8dea-1bba1af50dca', firstName='User', lastName='Name', username='user611552', addresses=[], cards=[]}, address=Address{addressId=null, id='8312d67d-411f-41d5-ac35-f2a4e36e481d', street_number='000', street='000 Example St.', city='City', postcode='90630', country='USA'}, card=Card{cardId=null, id='fba5b864-d311-4e96-971b-ac51acc4b75d', longNum='xxxxxxxxxxxx0000', expires='0000', ccv='null'}, items=[Item{sId=null, id='23c6e828-70b3-4973-96c3-59b73c34fb8c', itemId='MU-US-016', quantity=1, unitPrice=0.0}, Item{sId=null, id='db5cdfee-aa19-462b-ab37-a7da4a4549d5', itemId='MU-US-022', quantity=1, unitPrice=0.0}, Item{sId=null, id='7fc38c93-0dec-4a81-9a3c-bc01b2fa7ae9', itemId='MU-US-023', quantity=1, unitPrice=0.0}], shipment=null, orderDate=Thu Jun 03 09:47:16 GMT 2021, total=4.99]
Hibernate: select hibernate_sequence.nextval from dual
09:47:16.793 [RxCachedThreadScheduler-1] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: 2289, SQLState: 42000
09:47:16.793 [RxCachedThreadScheduler-1] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ORA-02289: sequence does not exist

09:47:16.795 [RxCachedThreadScheduler-1] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:726)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:706)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.lambda$persist$7(HibernateJpaOperations.java:434)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeWrite(AbstractSynchronousTransactionManager.java:175)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.persist(HibernateJpaOperations.java:430)
	at io.micronaut.data.runtime.intercept.DefaultSaveEntityInterceptor.intercept(DefaultSaveEntityInterceptor.java:46)
	at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:100)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:96)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:137)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:96)
	at mushop.orders.repositories.CustomerOrderRepository$Intercepted.save(Unknown Source)
	at mushop.orders.services.OrdersService.createOrder(OrdersService.java:180)
	at mushop.orders.services.$OrdersServiceDefinition$Intercepted.$$access$$createOrder(Unknown Source)
	at mushop.orders.services.$OrdersServiceDefinition$$exec2.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:151)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:87)
	at io.micronaut.transaction.interceptor.TransactionalInterceptor.intercept(TransactionalInterceptor.java:134)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:96)
	at mushop.orders.services.$OrdersServiceDefinition$Intercepted.createOrder(Unknown Source)
	at mushop.orders.services.OrdersService.lambda$placeOrder$10(OrdersService.java:146)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.micronaut.reactive.rxjava2.RxInstrumentedSingle.subscribeActual(RxInstrumentedSingle.java:52)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:553)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:63)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:67)
	at org.hibernate.id.enhanced.SequenceStructure$1.getNextValue(SequenceStructure.java:95)
	at org.hibernate.id.enhanced.NoopOptimizer.generate(NoopOptimizer.java:40)
	at org.hibernate.id.enhanced.SequenceStyleGenerator.generate(SequenceStyleGenerator.java:523)
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:115)
	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:185)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:128)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:55)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:102)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:720)
	... 34 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: ORA-02289: sequence does not exist

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:628)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:562)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1145)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:726)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:291)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:492)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:148)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:928)
	at oracle.jdbc.driver.OracleStatement.prepareDefineBufferAndExecute(OracleStatement.java:1158)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1093)
	at oracle.jdbc.driver.OracleStatement.executeSQLSelect(OracleStatement.java:1402)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1285)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3735)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3847)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1098)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)
	... 43 common frames omitted
Caused by: oracle.jdbc.OracleDatabaseException: ORA-02289: sequence does not exist

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:632)
	... 60 common frames omitted
```

After I have used graalvm (jit) version of orders then schema was created and after replacing the image again by native-image version the app works as expected.

**Comment by graemerocher** [comment]
Potential workaround is to use flyway to setup the schema for production until this is resolved. This issue surprises me since I am pretty sure we have hibernate native tests. I do wonder if it is again the configuration not taking effect in native somehow.

**Comment by dstepanov** [comment]
```
17:31:49.122 [main] INFO  i.m.context.DefaultBeanContext - Reading Startup environment from bootstrap.yml
17:31:49.539 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
17:31:58.128 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
17:31:58.151 [main] WARN  i.m.c.i.binder.jvm.JvmGcMetrics - GC notifications will not be available because MemoryPoolMXBeans are not provided by the JVM
17:31:58.171 [main] INFO  org.hibernate.Version - HHH000412: Hibernate ORM core version 5.4.24.Final
17:31:58.189 [main] INFO  o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
17:31:58.220 [main] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.Oracle12cDialect
Hibernate: create table address (address_id number(19,0) not null, city varchar2(255 char), country varchar2(255 char), id varchar2(255 char), postcode varchar2(255 char), street varchar2(255 char), street_number varchar2(255 char), primary key (address_id))
Hibernate: create table card (card_id number(19,0) not null, ccv varchar2(255 char), expires varchar2(255 char), id varchar2(255 char), long_num varchar2(255 char), primary key (card_id))
Hibernate: create table cart (id varchar2(255 char) not null, customer_customer_id number(19,0), primary key (id))
Hibernate: create table cart_item (cart_id varchar2(255 char) not null, items_s_id number(19,0) not null)
Hibernate: create table customer (customer_id number(19,0) not null, first_name varchar2(255 char), id varchar2(255 char), last_name varchar2(255 char), username varchar2(255 char), primary key (customer_id))
Hibernate: create table customer_address (customer_customer_id number(19,0) not null, addresses_address_id number(19,0) not null)
Hibernate: create table customer_card (customer_customer_id number(19,0) not null, cards_card_id number(19,0) not null)
Hibernate: create table customer_order (id number(19,0) not null, order_date timestamp not null, total float, address_address_id number(19,0), card_card_id number(19,0), customer_customer_id number(19,0), shipment_id varchar2(255 char), primary key (id))
Hibernate: create table customer_order_item (customer_order_id number(19,0) not null, items_s_id number(19,0) not null)
Hibernate: create table item (s_id number(19,0) not null, id varchar2(255 char), item_id varchar2(255 char), quantity number(10,0) not null, unit_price float not null, primary key (s_id))
Hibernate: create table shipment (id varchar2(255 char) not null, name varchar2(255 char), primary key (id))
Hibernate: alter table cart_item drop constraint UK_th9g8x130cj5ej2pxsqf9reh2
Hibernate: alter table cart_item add constraint UK_th9g8x130cj5ej2pxsqf9reh2 unique (items_s_id)
Hibernate: alter table customer_address drop constraint UK_jcyvwl9wa94nrxi16uo83hr7o
Hibernate: alter table customer_address add constraint UK_jcyvwl9wa94nrxi16uo83hr7o unique (addresses_address_id)
Hibernate: alter table customer_card drop constraint UK_3boe4dc5gclci7hvwp5cbxfkx
Hibernate: alter table customer_card add constraint UK_3boe4dc5gclci7hvwp5cbxfkx unique (cards_card_id)
Hibernate: alter table customer_order_item drop constraint UK_bimqclssva4i1e4k5a6o4kpxa
Hibernate: alter table customer_order_item add constraint UK_bimqclssva4i1e4k5a6o4kpxa unique (items_s_id)
Hibernate: create sequence hibernate_sequence start with 1 increment by  1
Hibernate: alter table cart add constraint FK9hpirec8qm60sghwjqvu0s6ic foreign key (customer_customer_id) references customer
Hibernate: alter table cart_item add constraint FK8pri3hjme52tpfa0vx3c253fs foreign key (items_s_id) references item
Hibernate: alter table cart_item add constraint FK1uobyhgl1wvgt1jpccia8xxs3 foreign key (cart_id) references cart
Hibernate: alter table customer_address add constraint FKacsnqexc02s578qs3dbtrp50m foreign key (addresses_address_id) references address
Hibernate: alter table customer_address add constraint FKigw0i0l1u44ub00t5xa5va3jo foreign key (customer_customer_id) references customer
Hibernate: alter table customer_card add constraint FKdgs9ysbx693hu71gyy931weje foreign key (cards_card_id) references card
Hibernate: alter table customer_card add constraint FKl435abm6s6slk3nojipxcqt2m foreign key (customer_customer_id) references customer
Hibernate: alter table customer_order add constraint FK2w5v8cn7lltb145yrpcbstrbt foreign key (address_address_id) references address
Hibernate: alter table customer_order add constraint FK4s9e1taurwx3ucjlr0ban0dfs foreign key (card_card_id) references card
Hibernate: alter table customer_order add constraint FKdbml7a9r45i4smr4cn7h67s3w foreign key (customer_customer_id) references customer
Hibernate: alter table customer_order add constraint FK6jmbqkjrax1lfqf2amy0cww7g foreign key (shipment_id) references shipment
Hibernate: alter table customer_order_item add constraint FKr8vx07jjsnls8ksnpk456bi4s foreign key (items_s_id) references item
Hibernate: alter table customer_order_item add constraint FK5vt6kkjrfyqqkwtr94rx7c1jr foreign key (customer_order_id) references customer_order
17:32:41.193 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 52209ms. Server Running: http://df138783f1c7:8082
```
I cannot reproduce this one, you can see seq. is being created for me.

**Comment by pgressa** [comment]
OK I have tested it against newly created ATP and it works. Let me try to create new mushop deployment, in case it won't work I'll give you access to the stack.

**Comment by pgressa** [comment]
deployed new stack, does not happening right now:
```
Jun 15, 2021 1:16:15 PM org.glassfish.jersey.message.internal.MessagingBinders$EnabledProvidersBinder bindToBinder
WARNING: A class java.awt.image.RenderedImage for a default provider MessageBodyWriter<java.awt.image.RenderedImage> was not found. The provider is not available.
pavol_gres@cloudshell:~ (us-ashburn-1)$ kubectl -n mushop logs mushop-orders-9cd9b57dd-qd8b7
/app/application: /usr/lib/libstdc++.so.6: no version information available (required by /app/application)
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v2.5.4)

13:15:11.839 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [k8s, cloud, oraclecloud]
13:15:11.840 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [k8s, cloud, oraclecloud]
13:15:11.842 [main] INFO  i.m.context.DefaultBeanContext - Reading Startup environment from bootstrap.yml
13:15:11.860 [main] INFO  com.oracle.bmc.Services - Registering new service: Services.BasicService(serviceName=DATABASE, serviceEndpointPrefix=database, serviceEndpointTemplate=https://database.{region}.{secondLevelDomain})
13:15:11.860 [main] INFO  com.oracle.bmc.Services - Registering new service: Services.BasicService(serviceName=AUTH, serviceEndpointPrefix=auth, serviceEndpointTemplate=null)
Jun 15, 2021 1:15:11 PM org.glassfish.jersey.message.internal.MessagingBinders$EnabledProvidersBinder bindToBinder
WARNING: A class java.awt.image.RenderedImage for a default provider MessageBodyWriter<java.awt.image.RenderedImage> was not found. The provider is not available.
13:15:11.867 [main] INFO  c.o.b.a.AbstractFederationClientAuthenticationDetailsProviderBuilder - Rest call to verify if v2 endpoint exists, response from v2 was 200
13:15:11.867 [main] INFO  c.o.b.a.AbstractFederationClientAuthenticationDetailsProviderBuilder -  Metadata base url on executing instance fallback is http://169.254.169.254/opc/v2/
Jun 15, 2021 1:15:11 PM org.glassfish.jersey.message.internal.MessagingBinders$EnabledProvidersBinder bindToBinder
WARNING: A class java.awt.image.RenderedImage for a default provider MessageBodyWriter<java.awt.image.RenderedImage> was not found. The provider is not available.
13:15:11.871 [main] INFO  c.o.b.a.AbstractFederationClientAuthenticationDetailsProviderBuilder - Looking up region for iad
13:15:11.872 [main] INFO  c.o.b.a.AbstractFederationClientAuthenticationDetailsProviderBuilder - Using region us-ashburn-1
13:15:11.872 [main] INFO  com.oracle.bmc.Region - Loaded service 'AUTH' endpoint mappings: {US_ASHBURN_1=https://auth.us-ashburn-1.oraclecloud.com}
13:15:11.872 [main] INFO  c.o.b.a.URLBasedX509CertificateSupplier - suppressX509Workaround flag set to false
13:15:12.657 [main] INFO  com.oracle.bmc.util.JavaRuntimeUtils - Determined JRE version as Unknown
13:15:12.657 [main] WARN  c.o.bmc.http.DefaultConfigurator - Using an unknown runtime, calls may not work
13:15:12.657 [main] INFO  c.o.bmc.http.DefaultConfigurator - Setting connector provider to HttpUrlConnectorProvider
13:15:12.658 [main] WARN  c.o.bmc.http.DefaultConfigurator - Using an unknown runtime, calls may not work
13:15:12.658 [main] INFO  c.o.bmc.http.DefaultConfigurator - Setting connector provider to HttpUrlConnectorProvider
13:15:12.658 [main] INFO  com.oracle.bmc.Region - Loaded service 'DATABASE' endpoint mappings: {US_ASHBURN_1=https://database.us-ashburn-1.oraclecloud.com}
13:15:12.658 [main] INFO  c.oracle.bmc.database.DatabaseClient - Setting endpoint to https://database.us-ashburn-1.oraclecloud.com
Jun 15, 2021 1:15:12 PM org.glassfish.jersey.message.internal.MessagingBinders$EnabledProvidersBinder bindToBinder
WARNING: A class java.awt.image.RenderedImage for a default provider MessageBodyWriter<java.awt.image.RenderedImage> was not found. The provider is not available.
13:15:12.674 [main] INFO  c.o.b.a.i.X509FederationClient - Refreshing session keys.
13:15:13.168 [main] INFO  c.o.b.a.i.X509FederationClient - Getting security token from the auth server
Jun 15, 2021 1:15:13 PM org.glassfish.jersey.message.internal.MessagingBinders$EnabledProvidersBinder bindToBinder
WARNING: A class java.awt.image.RenderedImage for a default provider MessageBodyWriter<java.awt.image.RenderedImage> was not found. The provider is not available.
13:15:13.186 [main] INFO  com.oracle.bmc.ClientRuntime - Using SDK: Oracle-JavaSDK/1.34.0
13:15:13.186 [main] INFO  com.oracle.bmc.ClientRuntime - User agent set to: Oracle-JavaSDK/1.34.0 (Linux/5.4.17-2102.201.3.el7uek.x86_64; Java/11.0.11; Substrate VM/GraalVM 21.1.0 Java 11 CE)
13:15:22.420 [main] INFO  i.m.o.a.j.OracleWalletArchiveProvider - Using default serviceAlias: MuShopMcUk_high
13:15:22.549 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
13:15:22.720 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
13:15:22.721 [main] INFO  com.oracle.bmc.Services - Registering new service: Services.BasicService(serviceName=MONITORING, serviceEndpointPrefix=telemetry, serviceEndpointTemplate=https://telemetry.{region}.{secondLevelDomain})
13:15:22.721 [main] WARN  c.o.bmc.http.DefaultConfigurator - Using an unknown runtime, calls may not work
13:15:22.721 [main] INFO  c.o.bmc.http.DefaultConfigurator - Setting connector provider to HttpUrlConnectorProvider
13:15:22.722 [main] INFO  com.oracle.bmc.Region - Loaded service 'MONITORING' endpoint mappings: {US_ASHBURN_1=https://telemetry.us-ashburn-1.oraclecloud.com}
13:15:22.722 [main] INFO  c.o.bmc.monitoring.MonitoringClient - Setting endpoint to https://telemetry.us-ashburn-1.oraclecloud.com
13:15:22.722 [main] INFO  c.o.bmc.monitoring.MonitoringClient - Authentication details provider configured for region 'US_ASHBURN_1', but endpoint specifically set to 'https://telemetry-ingestion.us-ashburn-1.oraclecloud.com'. Using endpoint setting instead of region.
13:15:22.722 [main] INFO  c.o.bmc.monitoring.MonitoringClient - Setting endpoint to https://telemetry-ingestion.us-ashburn-1.oraclecloud.com
13:15:22.722 [main] INFO  i.m.c.i.push.PushMeterRegistry - publishing metrics for OracleCloudMeterRegistry every 1m
13:15:22.723 [main] WARN  i.m.c.i.binder.jvm.JvmGcMetrics - GC notifications will not be available because MemoryPoolMXBeans are not provided by the JVM
13:15:22.724 [main] INFO  org.hibernate.Version - HHH000412: Hibernate ORM core version 5.4.24.Final
13:15:22.725 [main] INFO  o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
13:15:22.726 [main] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.Oracle12cDialect
Hibernate: create table address (address_id number(19,0) not null, city varchar2(255 char), country varchar2(255 char), id varchar2(255 char), postcode varchar2(255 char), street varchar2(255 char), street_number varchar2(255 char), primary key (address_id))
Hibernate: create table card (card_id number(19,0) not null, ccv varchar2(255 char), expires varchar2(255 char), id varchar2(255 char), long_num varchar2(255 char), primary key (card_id))
Hibernate: create table cart (id varchar2(255 char) not null, customer_customer_id number(19,0), primary key (id))
Hibernate: create table cart_item (cart_id varchar2(255 char) not null, items_s_id number(19,0) not null)
Hibernate: create table customer (customer_id number(19,0) not null, first_name varchar2(255 char), id varchar2(255 char), last_name varchar2(255 char), username varchar2(255 char), primary key (customer_id))
Hibernate: create table customer_address (customer_customer_id number(19,0) not null, addresses_address_id number(19,0) not null)
Hibernate: create table customer_card (customer_customer_id number(19,0) not null, cards_card_id number(19,0) not null)
Hibernate: create table customer_order (id number(19,0) not null, order_date timestamp not null, total float, address_address_id number(19,0), card_card_id number(19,0), customer_customer_id number(19,0), shipment_id varchar2(255 char), primary key (id))
Hibernate: create table customer_order_item (customer_order_id number(19,0) not null, items_s_id number(19,0) not null)
Hibernate: create table item (s_id number(19,0) not null, id varchar2(255 char), item_id varchar2(255 char), quantity number(10,0) not null, unit_price float not null, primary key (s_id))
Hibernate: create table shipment (id varchar2(255 char) not null, name varchar2(255 char), primary key (id))
Hibernate: alter table cart_item drop constraint UK_th9g8x130cj5ej2pxsqf9reh2
Hibernate: alter table cart_item add constraint UK_th9g8x130cj5ej2pxsqf9reh2 unique (items_s_id)
Hibernate: alter table customer_address drop constraint UK_jcyvwl9wa94nrxi16uo83hr7o
Hibernate: alter table customer_address add constraint UK_jcyvwl9wa94nrxi16uo83hr7o unique (addresses_address_id)
Hibernate: alter table customer_card drop constraint UK_3boe4dc5gclci7hvwp5cbxfkx
Hibernate: alter table customer_card add constraint UK_3boe4dc5gclci7hvwp5cbxfkx unique (cards_card_id)
Hibernate: alter table customer_order_item drop constraint UK_bimqclssva4i1e4k5a6o4kpxa
Hibernate: alter table customer_order_item add constraint UK_bimqclssva4i1e4k5a6o4kpxa unique (items_s_id)
Hibernate: create sequence hibernate_sequence start with 1 increment by  1
Hibernate: alter table cart add constraint FK9hpirec8qm60sghwjqvu0s6ic foreign key (customer_customer_id) references customer
Hibernate: alter table cart_item add constraint FK8pri3hjme52tpfa0vx3c253fs foreign key (items_s_id) references item
Hibernate: alter table cart_item add constraint FK1uobyhgl1wvgt1jpccia8xxs3 foreign key (cart_id) references cart
Hibernate: alter table customer_address add constraint FKacsnqexc02s578qs3dbtrp50m foreign key (addresses_address_id) references address
Hibernate: alter table customer_address add constraint FKigw0i0l1u44ub00t5xa5va3jo foreign key (customer_customer_id) references customer
Hibernate: alter table customer_card add constraint FKdgs9ysbx693hu71gyy931weje foreign key (cards_card_id) references card
Hibernate: alter table customer_card add constraint FKl435abm6s6slk3nojipxcqt2m foreign key (customer_customer_id) references customer
Hibernate: alter table customer_order add constraint FK2w5v8cn7lltb145yrpcbstrbt foreign key (address_address_id) references address
Hibernate: alter table customer_order add constraint FK4s9e1taurwx3ucjlr0ban0dfs foreign key (card_card_id) references card
Hibernate: alter table customer_order add constraint FKdbml7a9r45i4smr4cn7h67s3w foreign key (customer_customer_id) references customer
Hibernate: alter table customer_order add constraint FK6jmbqkjrax1lfqf2amy0cww7g foreign key (shipment_id) references shipment
Hibernate: alter table customer_order_item add constraint FKr8vx07jjsnls8ksnpk456bi4s foreign key (items_s_id) references item
Hibernate: alter table customer_order_item add constraint FK5vt6kkjrfyqqkwtr94rx7c1jr foreign key (customer_order_id) references customer_order
13:15:24.372 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 12540ms. Server Running: http://mushop-orders-9cd9b57dd-qd8b7:8082
13:15:24.701 [default-nioEventLoopGroup-1-5] INFO  i.m.context.DefaultBeanContext - Reading Startup environment from bootstrap.yml
13:15:24.702 [default-nioEventLoopGroup-1-5] INFO  i.m.context.DefaultBeanContext - Reading Startup environment from bootstrap.yml
13:15:24.703 [default-nioEventLoopGroup-1-5] INFO  i.m.context.DefaultBeanContext - Reading Startup environment from bootstrap.yml
13:15:24.704 [default-nioEventLoopGroup-1-5] INFO  i.m.context.DefaultBeanContext - Reading Startup environment from bootstrap.yml
13:15:24.706 [default-nioEventLoopGroup-1-5] INFO  i.m.context.DefaultBeanContext - Reading Startup environment from bootstrap.yml
13:15:24.707 [default-nioEventLoopGroup-1-5] INFO  i.m.context.DefaultBeanContext - Reading Startup environment from bootstrap.yml
Jun 15, 2021 1:16:22 PM org.glassfish.jersey.message.internal.MessagingBinders$EnabledProvidersBinder bindToBinder
```
