### ISSUE TITLE
build: Pipeline fails for Java 16 b/c of jdbi in groovy

### ISSUE THREAD

**Issue by pgressa** [micronaut-projects/micronaut-sql#507]
### Expected Behavior

pipeline passes

### Actual Behaviour

The tests fails for java16.
```
Task :jdbi:test
io.micronaut.configuration.jdbi.JdbiSpec test blank configuration PASSED (1.1s)
io.micronaut.configuration.jdbi.JdbiSpec test plugins PASSED
io.micronaut.configuration.jdbi.JdbiSpec test simple sql FAILED

  java.lang.reflect.InvocationTargetException
      at org.codehaus.groovy.vmplugin.v9.Java9.of(Java9.java:160)
      at org.codehaus.groovy.vmplugin.v9.Java9.getInvokeSpecialHandle(Java9.java:179)
      at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
      at org.jdbi.v3.core.Jdbi.useHandle(Jdbi.java:358)
      at io.micronaut.configuration.jdbi.JdbiSpec.cleanupDatabase(JdbiSpec.groovy:224)
      at io.micronaut.configuration.jdbi.JdbiSpec.test simple sql(JdbiSpec.groovy:102)
  Caused by: java.lang.IllegalAccessException: module jdk.proxy3 does not open jdk.proxy3 to unnamed module @815b41f
      at java.base/java.lang.invoke.MethodHandles.privateLookupIn(MethodHandles.java:260)
      ... 6 more

```

### Version

3.0.1

**Comment by pgressa** [comment]
According to https://issues.apache.org/jira/browse/GROOVY-10145 it is fixed in grovvy 4.0.0, and based on the comment the  https://issues.apache.org/jira/browse/GROOVY-10194 should address this as well.
