### ISSUE TITLE
Outdated documentation for JDBC Transaction management

### ISSUE THREAD

**Issue by chrisparton1991** [micronaut-projects/micronaut-sql#558]

**Comment by graemerocher** [comment]
@burtbeckwith could you add some docs on using Micronaut SQL with Micronaut TX without Micronaut Data to address this issue.

**Comment by matt-snider** [comment]
@graemerocher @burtbeckwith  Very much appreciated :pray:

**Comment by viniciusxyz** [comment]
Some of these problems were reported in issue #555, in which case I sent an MR with the correction of part of the mentioned problems.

**Comment by matt-snider** [comment]
@burtbeckwith Do you have any guidance here? Haven't found a way to get `@Transactional` to work with or without `micronaut-data`. Is there a minimal project that shows this working?

**Comment by matt-snider** [comment]
Okay I've been struggling with this one for awhile and it turns out the `TransactionalInterceptor` has been getting applied the whole time. The issue is that any methods not annotated with `@Transactional` throw an exception and this lead me to believe something was very wrong with my setup.

```

Unexpected error occurred: No current transaction present. Consider declaring @Transactional on the surrounding method
io.micronaut.transaction.exceptions.NoTransactionException: No current transaction present. Consider declaring @Transactional on the surrounding method
	at io.micronaut.transaction.jdbc.TransactionalConnectionInterceptor.intercept(TransactionalConnectionInterceptor.java:65)
       // omitted
Caused by: io.micronaut.transaction.jdbc.exceptions.CannotGetJdbcConnectionException: No current JDBC Connection found. Consider wrapping this call in transactional boundaries.
	at io.micronaut.transaction.jdbc.DataSourceUtils.doGetConnection(DataSourceUtils.java:135)
	at io.micronaut.transaction.jdbc.DataSourceUtils.getConnection(DataSourceUtils.java:93)
```

So obviously I'm doing something wrong here because the [Transactions Guide](https://micronaut-projects.github.io/micronaut-data/latest/guide/#transactions) doesn't mention anything about all methods requiring the annotation (that wouldn't make sense?),  In fact it even says:

> You can simply declare a method as transactional with the javax.transaction.Transactional annotation.

You can see the [`TestController`](https://github.com/matt-snider/micronaut-tx-issues/blob/master/src/main/java/com/example/TestController.java) in a repository I created to exemplify the issue

**Comment by matt-snider** [comment]
I was able to get transactions working without Spring by adding the dependencies
 `annotationProcessor("io.micronaut.data:micronaut-data-processor:3.2.2")` and `implementation("io.micronaut.data:micronaut-data-tx")`. It turns out that the `NoTransactionException` was caused by a bug which I reported in #1399

This issue was about outdated docs, so I hope I didn't derail the discussion too much. Still I wonder if the documentation should be improved here. There is a main section under JDBC about how to use Spring Transactions, but no such section about how to add Micronaut Transactions. Unless there is some reason `micronaut-sql` + `micronaut-data-tx` are not recommend together, I think we should document this more clearly, otherwise most users will probably just set up Spring Transactions.

**Comment by morki** [comment]
For me, personally, it was also confusing the first time, because we don't use `micronaut-data` but need the `micronaut-data-tx` to use with `micronaut-sql`. Maybe the transactions module should be transfered to `micronaut-sql` the same as is the reactive transactions module located in `micronaut-r2dbc`?

**Comment by matt-snider** [comment]
I just ran into this again because I was trying to get JOOQ set up properly such that I have the `JooqExceptionTranslator` and Transaction Manager from Spring but it doesn't seem to work. It seems like I get proper exception messages with `compileOnly("org.springframework:spring-jdbc")` but then I don't have the transaction manager, and with `runtimeOnly("org.springframework:spring-jdbc")` the transaction manager works but not the informative exceptions.

I think what I will try is to remove Spring Transaction management and switch to Micronaut and then implement my own JOOQ exception handler.

I think the documentation would be more clear with a subsection in JOOQ explaining how to set up Transaction management for each scenario (with Spring, without Spring) as well as how to get the `JooqExceptionTranslator` working properly

**Comment by MT-Jacobs** [comment]
This documentation is definitely missing. I'm currently trying to read through some tests that use transactions in this project; if the transactions work in the test, then the build.gradle must sufficiently add the right dependencies for transactions to work.

**Comment by MT-Jacobs** [comment]
Looks like, at minimum, you need to add:
```
io.micronaut.data:micronaut-data-processor
io.micronaut.data:micronaut-data-tx
```
So, for Kotlin, assuming hikari:
```kts
dependencies {
	kapt("io.micronaut.data:micronaut-data-processor")
	implementation("io.micronaut.data:micronaut-data-tx")
	implementation("io.micronaut.sql:micronaut-jdbi")
	runtimeOnly("io.micronaut.sql:micronaut-jdbc-hikari")
}
```
In short, you must include some Micronaut Data dependencies to get transaction management working in Micronaut SQL if you're not using Micronaut Spring.

**Comment by MT-Jacobs** [comment]
The documentation is still out of date. Regrettably, it looks like Micronaut 4 has made the docs _even more_ out of date - my instructions are no longer accurate.

Can we have someone with a bit more Micronaut SQL expertise provide some direction on how to properly use transactions when not using Micronaut Data, assuming that's still supported?

**Comment by MT-Jacobs** [comment]
Here's the new dependency that's now needed:

```
implementation("io.micronaut.data:micronaut-data-tx")
```
