### ISSUE TITLE
GraalVM 22.2 fails with NoClassDefFoundError: Could not initialize class org.mariadb.jdbc.internal.protocol.MasterProtocol

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-sql#705]
Steps to reproduce: 

- [Clone repository `micronaut-graal-tests/micronaut-data-jdbc-graal` branch `3.6.x_mariadb`](https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal/tree/3.6.x_mariadb). 

Start maria locally via Docker. The app expects a `pets` database to exists and credentials: 

https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal/blob/3.6.x_mariadb/src/main/resources/application.yml#L9-L12

- Use GraalVM 22.2 `sdk use java 22.2.r11-grl`
- Build Native Image with ` ./build-native-image.sh`
- Execute Native Image `./data-jdbc-mariadb`

```   
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v3.6.0-SNAPSHOT)

11:23:53.579 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
11:23:53.580 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]

Message: Could not initialize class org.mariadb.jdbc.internal.protocol.MasterProtocol
Path Taken: DataSource.dataSource(DatasourceConfiguration datasourceConfiguration)
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [javax.sql.DataSource]

Message: Could not initialize class org.mariadb.jdbc.internal.protocol.MasterProtocol
Path Taken: DataSource.dataSource(DatasourceConfiguration datasourceConfiguration)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1915)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:245)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3320)
	at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3678)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:341)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:190)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:75)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:323)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:309)
	at example.Application.main(Application.java:30)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [javax.sql.DataSource]

Message: Could not initialize class org.mariadb.jdbc.internal.protocol.MasterProtocol
Path Taken: DataSource.dataSource(DatasourceConfiguration datasourceConfiguration)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2361)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2299)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2245)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3010)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2912)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2731)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1909)
	... 9 common frames omitted
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.mariadb.jdbc.internal.protocol.MasterProtocol
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:632)
	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150)
	at org.mariadb.jdbc.Driver.connect(Driver.java:89)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at io.micronaut.configuration.jdbc.hikari.HikariUrlDataSource.<init>(HikariUrlDataSource.java:35)
	at io.micronaut.configuration.jdbc.hikari.DatasourceFactory.dataSource(DatasourceFactory.java:66)
	at io.micronaut.configuration.jdbc.hikari.$DatasourceFactory$DataSource0$Definition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:161)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2348)
	... 16 common frames omitted
````

Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.mariadb.jdbc.internal.protocol.MasterProtocol 87

see: https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2789498615
see: https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2789470817
https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2789497223

**Comment by sdelamo** [comment]
I have tried downgrading the driver in the https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal/tree/3.6.x_mariadb to 2.7.5 

with 

```groovy
  ...
 runtimeOnly("org.mariadb.jdbc:mariadb-java-client:2.7.5")
}


configurations.all {
    resolutionStrategy {
        force "org.mariadb.jdbc:mariadb-java-client:2.7.5"
    }
}
```

But the error still happens.

**Comment by sdelamo** [comment]
I assume we need to do a change here:

https://github.com/micronaut-projects/micronaut-sql/blob/master/jdbc/src/main/java/io/micronaut/jdbc/nativeimage/JdbcFeature.java#L134-L139

**Comment by dstepanov** [comment]
Can you reproduce the problem in a pr to the project? We run graalvm tests here

**Comment by sdelamo** [comment]
> Can you reproduce the problem in a pr to the project? We run graalvm tests here

[SQL PRs](https://github.com/micronaut-projects/micronaut-sql/pull/690 ) are already failing https://github.com/micronaut-projects/micronaut-sql/runs/7588418263?check_suite_focus=true because of the issue

**Comment by graemerocher** [comment]
It seems to be failing somehow because `javax.sql.rowset.serial.SerialException` is missing

**Comment by graemerocher** [comment]
it works when using:

```
export USE_NATIVE_IMAGE_JAVA_PLATFORM_MODULE_SYSTEM=false
```

**Comment by graemerocher** [comment]
@melix seems we need to add imports for the `javax.sql` package as well :(

**Comment by melix** [comment]
Can you try with this?

```gradle
graalvmNative {
   binaries.all {
      jvmArgs("--add-exports=org.graalvm.nativeimage.builder/javax.sql=ALL-UNNAMED")
   }
}
```

**Comment by graemerocher** [comment]
yes that works

**Comment by melix** [comment]
Do we want to release a new version of the Gradle plugin with the fix or is the workaround sufficient?

**Comment by sdelamo** [comment]
I think we should do a patch of the Gradle plugin

**Comment by olpaw** [comment]
> Can you try with this?
> 
> ```groovy-gradle
> graalvmNative {
>    binaries.all {
>       jvmArgs("--add-exports=org.graalvm.nativeimage.builder/javax.sql=ALL-UNNAMED")
>    }
> }
> ```

That does not make sense. Module `org.graalvm.nativeimage.builder` does not contain package `javax.sql`. If you try that on a simple native-image command line invocation you see that it makes no sense:
```
$ bin/native-image --add-exports=org.graalvm.nativeimage.builder/javax.sql=ALL-UNNAMED -jar HelloWorld.jar
Fatal error: java.lang.IllegalArgumentException: package javax.sql not in contents
	at java.base/java.lang.Module.implAddExportsOrOpens(Module.java:940)
	at java.base/java.lang.Module.implAddExportsToAllUnnamed(Module.java:868)
	at java.base/java.lang.System$2.addExportsToAllUnnamed(System.java:2347)
	at java.base/jdk.internal.module.Modules.addExportsToAllUnnamed(Modules.java:119)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageClassLoaderSupport.lambda$processClassLoaderOptions$7(NativeImageClassLoaderSupport.java:359)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageClassLoaderSupport.processClassLoaderOptions(NativeImageClassLoaderSupport.java:357)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageClassLoaderOptions$ApplyNativeImageClassLoaderOptions.apply(NativeImageClassLoaderOptions.java:54)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.installNativeImageClassLoader(NativeImageGeneratorRunner.java:184)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:123)
Error: Image build request failed with exit status 1
```

**Comment by timyates** [comment]
Do we just need to add

```
            initializeAtBuildTime(access, "javax.sql.rowset.serial.SerialException");
```

To JdbcFeature?

**Comment by sdelamo** [comment]
> Do we just need to add
> 
> ```
>             initializeAtBuildTime(access, "javax.sql.rowset.serial.SerialException");
> ```
> 
> To JdbcFeature?

Thanks @timyates  I tried locally and it works. I. have created a PR. https://github.com/micronaut-projects/micronaut-sql/pull/709

@melix  This way, we don't need to apply the fix to the Gradle plugin. Thus, Maven users will get the fix as well.

**Comment by timyates** [comment]
@sdelamo hang file...

Not sure it does work with 22.2 😿

**Comment by melix** [comment]
Yeah I'm confused because we paired with @fniephaus and tried this without success. Fabio is trying to pin the root cause.

**Comment by sdelamo** [comment]
> @sdelamo hang file...
> 
> Not sure it does work with 22.2 😿

I think I tried with 22.2. I will try again.

**Comment by fniephaus** [comment]
I looked into this with @olpaw and just opened #710 which fixes the issue. The problem is that the Native Image builder opened packages for the unnamed module (so essentially for everyone), including the `java.sql` modules, when it was running on the class path. Now, that is runs on the module path, this no longer happens, which is good and part of the reason why the builder now runs on the module path in the first place. However, the MariaDB connector requires `java.sql.rowset`. In the 22.3 release, Native Image will pre-populate this and other modules when user applications are not making use of modules. In the meantime, `java.sql.rowset` needs to be added explicitly, which is exactly what #710 does.

**Comment by melix** [comment]
I'm still getting an error with ` initializeAtBuildTime(access, "javax.sql.rowset.serial.SerialException");` but it seems to be a timeout in starting the containers: https://ge.micronaut.io/s/fahoased2ypqk/tests/:tests:hibernate5:hibernate5-mariadb:testNativeImage/example.sync.MariaDBAppSpec/initializationError?expanded-stacktrace=WyIwIl0&top-execution=1

```
io.micronaut.http.server.exceptions.ServerStartupException: Timeout occurred starting Micronaut process server
	at app//io.micronaut.test.support.server.TestExecutableEmbeddedServer.start(TestExecutableEmbeddedServer.java:212)
	at app//io.micronaut.test.support.server.TestExecutableEmbeddedServer.start(TestExecutableEmbeddedServer.java:56)
	at app//io.micronaut.test.extensions.AbstractMicronautExtension.beforeClass(AbstractMicronautExtension.java:243)
	at app//io.micronaut.test.extensions.spock.MicronautSpockExtension.lambda$visitSpecAnnotation$3(MicronautSpockExtension.java:95)
	at app//org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:101)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:148)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base@11.0.16/java.util.ArrayList.forEach(ArrayList.java:1541)
```

**Comment by melix** [comment]
Thank you @fniephaus !

**Comment by timyates** [comment]
> I'm still getting an error with ` initializeAtBuildTime(access, "javax.sql.rowset.serial.SerialException");`

Yeah, that was me getting excited and picking 22.1 instead of 22.2 for testing :-(. Sorry about that TooManyJvmsException

**Comment by sdelamo** [comment]
@fniephaus Thanks for the help.
