### ISSUE TITLE
Outdated micronaut version

### ISSUE THREAD

**Issue by fmayoral** [micronaut-projects/micronaut-sql#8]
Micronaut version are misaligned for this version, see dep tree
```
[INFO] +- io.micronaut.configuration:micronaut-jdbc-hikari:jar:1.1.0:compile
[INFO] |  +- io.micronaut:micronaut-jdbc:jar:1.0.4:compile
[INFO] |  +- io.micronaut:micronaut-inject:jar:1.0.4:compile
[INFO] |  |  \- io.micronaut:micronaut-core:jar:1.0.4:compile
[INFO] |  |     \- org.reactivestreams:reactive-streams:jar:1.0.2:compile
[INFO] |  \- com.zaxxer:HikariCP:jar:3.3.1:compile
```

**Comment by graemerocher** [comment]
It is not misaligned, the library still supports Micronaut 1.0.4 to align the versions correctly you should use the `micronaut-bom` for 1.1.0 which will ensure the correct transitives are used.

**Comment by bufferings** [comment]
@graemerocher I understood your thought and I agree.

I'm not sure here is the right place to ask, but I have a question related 1.1.0. When I replaced `micronautVersion` to `1.1.0` in `gradle.properties` and run `./gradlew check`, a test fails:
```
Expected exception of type 'java.lang.RuntimeException', but got 'java.lang.Exception'
	at org.spockframework.lang.SpecInternals.checkExceptionThrown(SpecInternals.java:80)
	at org.spockframework.lang.SpecInternals.thrownImpl(SpecInternals.java:67)
	at io.micronaut.configuration.hibernate.jpa.JpaSetupSpec.test spring based transaction management(JpaSetupSpec.groovy:153)
Caused by: java.lang.Exception: bad things happened
	at io.micronaut.configuration.hibernate.jpa.BookService.saveError(JpaSetupSpec.groovy:226)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:144)
	at io.micronaut.aop.chain.InterceptorChain.lambda$new$1(InterceptorChain.java:89)
	at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:146)
	at io.micronaut.spring.tx.annotation.TransactionInterceptor.intercept(TransactionInterceptor.java:81)
	at io.micronaut.aop.MethodInterceptor.intercept(MethodInterceptor.java:40)
	at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:146)
	at io.micronaut.configuration.hibernate.jpa.JpaSetupSpec.test spring based transaction management(JpaSetupSpec.groovy:150)
```

I briefly debugged the code and found that with `1.0.4`, the exception is caught here:

https://github.com/spring-projects/spring-framework/blob/v5.1.5.RELEASE/spring-tx/src/main/java/org/springframework/transaction/support/TransactionTemplate.java#L150

But with `1.1.0`, it doesn't be caught there, but here:

https://github.com/micronaut-projects/micronaut-core/blob/v1.1.0/spring/src/main/java/io/micronaut/spring/tx/annotation/TransactionInterceptor.java#L84

That's why the test fails with `1.1.0`, but I don't know the root cause.

It would be great help for me if you kindly tell me some advises, because I'm currently thinking to send pull request which depends on `1.1.0`.

**Comment by graemerocher** [comment]
Yeah it is more an error in the test, the test just needs to be updated to check for Exception instead of RuntimeException

**Comment by graemerocher** [comment]
btw the library can now be updated to 1.1.0 but when we do so we need to change the the version to 1.2.0.BUILD-SNAPSHOT

**Comment by bufferings** [comment]
Thank you!

> the test just needs to be updated to check for Exception instead of RuntimeException

I understood that Exception is the correct expected value for 1.1.0.

> we need to change the the version to 1.2.0.BUILD-SNAPSHOT

I got it. When I send pull request, I will change the projectVersion of micronaut-sql to 1.2.0.BUILD-SNAPSHOT

**Comment by fmayoral** [comment]
> It is not misaligned, the library still supports Micronaut 1.0.4 to align the versions correctly you should use the `micronaut-bom` for 1.1.0 which will ensure the correct transitives are used.

I see, thanks!
