### ISSUE TITLE
java.sql.rowset native image build issue

### ISSUE THREAD

**Issue by slatkovic** [micronaut-projects/micronaut-sql#868]
### Issue description

Hi folks, we've been running into a pesky issue when building a native image that has a dependency on **micronaut-jdbc-hikari**.

Looks like the native image config in **micronaut-jdbc** [**native-image.properties**](https://github.com/micronaut-projects/micronaut-sql/blob/master/jdbc/src/main/resources/META-INF/native-image/io.micronaut.sql/micronaut-jdbc/native-image.properties#L17) file is considered invalid; 
more specifically the following line: `--add-modules=java.sql.rowset`.

Any pointers here? 

```
Step #0: Step 9/13 : RUN native-image -cp /home/app/libs/*.jar:/home/app/resources:/home/app/application.jar --no-fallback -H:Name=application -H:ConfigurationFileDirectories=/home/app/config-dirs/generateResourcesConfigFile -H:Class=com.test.ApplicationKt --verbose -H:+ReportExceptionStackTraces --report-unsupported-elements-at-runtime
Step #0:  ---> Running in 3846e79
Step #0: Error: Processing jar:file:///home/app/libs/micronaut-jdbc-4.8.0.jar!/META-INF/native-image/io.micronaut.sql/micronaut-jdbc/native-image.properties failed
Step #0: Caused by: com.oracle.svm.driver.NativeImage$NativeImageError: Property 'Args' contains invalid entry '--add-modules=java.sql.rowset'
Step #0: com.oracle.svm.driver.NativeImage$NativeImageError: Processing jar:file:///home/app/libs/micronaut-jdbc-4.8.0.jar!/META-INF/native-image/io.micronaut.sql/micronaut-jdbc/native-image.properties failed
Step #0: 	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1758)
Step #0: 	at com.oracle.svm.driver.NativeImage.processClasspathNativeImageMetaInf(NativeImage.java:892)
Step #0: 	at com.oracle.svm.driver.NativeImage.addImageClasspathEntry(NativeImage.java:1647)
Step #0: 	at com.oracle.svm.driver.NativeImage.handleClassPathAttribute(NativeImage.java:983)
Step #0: 	at com.oracle.svm.driver.NativeImage.processJarManifestMainAttributes(NativeImage.java:945)
Step #0: 	at com.oracle.svm.driver.NativeImage.processManifestMainAttributes(NativeImage.java:935)
Step #0: 	at com.oracle.svm.driver.NativeImage.addImageClasspathEntry(NativeImage.java:1646)
Step #0: 	at com.oracle.svm.driver.NativeImage.addCustomImageClasspath(NativeImage.java:1616)
Step #0: 	at com.oracle.svm.driver.DefaultOptionHandler.processClasspathArgs(DefaultOptionHandler.java:536)
Step #0: 	at com.oracle.svm.driver.DefaultOptionHandler.consume(DefaultOptionHandler.java:123)
Step #0: 	at com.oracle.svm.driver.NativeImage$NativeImageArgsProcessor.apply(NativeImage.java:1547)
Step #0: 	at com.oracle.svm.driver.NativeImage.processNativeImageArgs(NativeImage.java:1802)
Step #0: 	at com.oracle.svm.driver.NativeImage.completeImageBuild(NativeImage.java:989)
Step #0: 	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1464)
Step #0: 	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1434)
Step #0: 	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1421)
Step #0: Caused by: com.oracle.svm.driver.NativeImage$NativeImageError: Property 'Args' contains invalid entry '--add-modules=java.sql.rowset'
Step #0: 	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1754)
Step #0: 	at com.oracle.svm.driver.NativeImage$NativeImageArgsProcessor.apply(NativeImage.java:1555)
Step #0: 	at com.oracle.svm.driver.NativeImage$DriverMetaInfProcessor.processMetaInfResource(NativeImage.java:614)
Step #0: 	at com.oracle.svm.driver.metainf.NativeImageMetaInfWalker.processNativeImageMetaInf(NativeImageMetaInfWalker.java:118)
Step #0: 	at com.oracle.svm.driver.metainf.NativeImageMetaInfWalker.walkMetaInfForCPEntry(NativeImageMetaInfWalker.java:88)
Step #0: 	at com.oracle.svm.driver.NativeImage.processClasspathNativeImageMetaInf(NativeImage.java:890)
Step #0: 	... 14 more
```

**Comment by slatkovic** [comment]
found the culprit: stale version of `io.micronaut.application` plugin
